import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SESIONES = [
  {
    numero: 1, bloque: "Bloque A · La empresa", bloqueLetra: "A", semana: 1,
    titulo: "Qué es Mainstage Pro",
    descripcion: "La sesión base del módulo. Establece qué somos, qué no somos y por qué importa lo que hacemos.",
    objetivos: ["Comprender qué es Mainstage Pro y su propuesta de valor", "Entender la promesa de marca y la diferenciación"],
    puntosBase: [
      "Qué es una empresa de producción técnica para eventos",
      "Qué hacemos y qué no hacemos — la línea que importa tener clara",
      "De dónde venimos y hacia dónde vamos",
      "Nuestra promesa de marca: de qué nos hacemos cargo exactamente",
      "Por qué importa lo que hacemos aunque nadie nos vea en el evento",
    ],
  },
  {
    numero: 2, bloque: "Bloque A · La empresa", bloqueLetra: "A", semana: 1,
    titulo: "Los servicios que ofrecemos",
    descripcion: "Cada servicio del portafolio: qué incluye, para qué sirve y cómo se combina.",
    objetivos: ["Conocer cada servicio del portafolio en detalle", "Entender cómo se combinan los servicios en un proyecto"],
    puntosBase: [
      "Audio profesional para eventos: qué incluye y qué no",
      "Iluminación: tipos de servicio y contextos de uso",
      "Video y pantallas: configuraciones y posibilidades",
      "Energía y planta de luz",
      "Estructuras, staging y entarimado",
      "DJ setup y rider técnico",
      "Coordinación técnica integral: qué significa ser el único responsable",
      "Cómo se combinan los servicios en un solo proyecto",
    ],
  },
  {
    numero: 3, bloque: "Bloque A · La empresa", bloqueLetra: "A", semana: 2,
    titulo: "Los clientes que atendemos",
    descripcion: "Criterio de selección de clientes: a quién sí, a quién no y por qué esa línea protege al equipo.",
    objetivos: ["Identificar los tipos de cliente que Mainstage Pro atiende", "Reconocer señales de alerta en un prospecto"],
    puntosBase: [
      "Quién nos contrata y por qué nos contrata",
      "Qué busca cada tipo de cliente: seguridad, imagen, precio, experiencia",
      "Criterio de selección: a qué clientes sí atendemos y a cuáles no",
      "Por qué elegir bien al cliente protege al equipo y al negocio",
      "Señales de alerta de un cliente que no es para nosotros",
    ],
  },
  {
    numero: 4, bloque: "Bloque B · Tipos de eventos", bloqueLetra: "B", semana: 2,
    titulo: "Eventos musicales",
    descripcion: "Conciertos, festivales y shows en vivo. Rider, tiempos y coordinación artística.",
    objetivos: ["Comprender las particularidades técnicas de eventos musicales", "Conocer los retos del rider artístico y coordinación"],
    puntosBase: [
      "Qué es un evento musical en el contexto de Mainstage Pro",
      "Tipos: conciertos, festivales, presentaciones en vivo, foros",
      "Necesidades técnicas específicas de este tipo de evento",
      "Quién nos contrata y qué espera",
      "Retos particulares: rider del artista, tiempos de montaje, coordinación artística",
      "Estándar de calidad que Mainstage Pro debe cumplir en este segmento",
    ],
  },
  {
    numero: 5, bloque: "Bloque B · Tipos de eventos", bloqueLetra: "B", semana: 3,
    titulo: "Eventos sociales",
    descripcion: "Bodas, quinceañeras y celebraciones privadas. El cliente emocional y el margen de error cero.",
    objetivos: ["Entender la naturaleza emocional del cliente en eventos sociales", "Conocer los estándares de servicio para este segmento"],
    puntosBase: [
      "Qué es un evento social: bodas, quinceañeras, celebraciones privadas",
      "Particularidades: el cliente es emocional, el margen de error es cero",
      "Necesidades técnicas: iluminación de ambiente, audio para DJ y voz, pantallas",
      "Quién nos contrata y qué espera",
      "Cómo se diferencia la atención al cliente en eventos sociales",
      "Estándar de calidad en este segmento",
    ],
  },
  {
    numero: 6, bloque: "Bloque B · Tipos de eventos", bloqueLetra: "B", semana: 3,
    titulo: "Eventos corporativos",
    descripcion: "Congresos, lanzamientos y convenciones. Cliente institucional con imagen de marca en juego.",
    objetivos: ["Conocer el perfil del cliente corporativo", "Entender los requerimientos técnicos y de protocolo"],
    puntosBase: [
      "Qué es un evento corporativo: congresos, lanzamientos, convenciones, cenas",
      "Particularidades: cliente institucional, imagen de marca en juego",
      "Necesidades técnicas: audio de conferencia, video, iluminación, streaming",
      "Quién nos contrata y qué espera",
      "Tiempos, formalismos y protocolo con este tipo de cliente",
      "Estándar de calidad en este segmento",
    ],
  },
  {
    numero: 7, bloque: "Bloque B · Tipos de eventos", bloqueLetra: "B", semana: 4,
    titulo: "Otros tipos de eventos",
    descripcion: "Deportivos, comedia, teatro, escuelas. Menos frecuentes pero estratégicamente importantes.",
    objetivos: ["Identificar otros segmentos de eventos atendibles", "Entender cómo adaptar el servicio a contextos distintos"],
    puntosBase: [
      "Eventos deportivos: torneos, inauguraciones, premiaciones",
      "Eventos de comedia: stand up, shows de humor, giras",
      "Teatro y artes escénicas: obras, musicales, danza, performance",
      "Eventos escolares y universitarios: graduaciones, festivales, semanas culturales",
      "Eventos gubernamentales e institucionales",
      "Por qué estos eventos son menos frecuentes pero estratégicamente importantes",
      "Cómo adaptar nuestro servicio a contextos y clientes distintos",
    ],
  },
  {
    numero: 8, bloque: "Bloque C · El inventario", bloqueLetra: "C", semana: 4,
    titulo: "Nuestro inventario: la base del negocio",
    descripcion: "79 equipos propios. Por qué el inventario define la capacidad y la rentabilidad.",
    objetivos: ["Comprender el valor estratégico del inventario propio", "Entender la diferencia entre equipo propio y subarrendado"],
    puntosBase: [
      "Por qué el inventario es la principal fuente de trabajo de Mainstage Pro",
      "Qué significa tener 79 equipos disponibles y cómo se traduce en capacidad de servicio",
      "Diferencia entre equipo propio y equipo subarrendado",
      "Por qué el estado del inventario afecta directamente la rentabilidad",
      "Cómo se decide cuándo comprar equipo nuevo",
    ],
  },
  {
    numero: 9, bloque: "Bloque C · El inventario", bloqueLetra: "C", semana: 5,
    titulo: "Categorías del inventario: audio",
    descripcion: "Consolas, cabinets, micrófonos y cables. Qué es cada cosa y para qué sirve.",
    objetivos: ["Conocer el inventario de audio de Mainstage Pro", "Identificar el uso correcto de cada equipo de audio"],
    puntosBase: [
      "Consolas de audio: tipos y usos",
      "Cabinets, subwoofers y monitores de piso: función y contextos",
      "Micrófonos alámbricos e inalámbricos, DI boxes, cables y snakes",
      "En qué tipo de eventos se usa cada equipo",
      "Señales básicas de que un equipo de audio no está funcionando bien",
      "Cómo se cuida y mantiene el equipo de audio",
    ],
  },
  {
    numero: 10, bloque: "Bloque C · El inventario", bloqueLetra: "C", semana: 5,
    titulo: "Categorías del inventario: iluminación",
    descripcion: "Par LED, moving heads, consolas y DMX. Todo lo que necesitas saber del inventario de luz.",
    objetivos: ["Conocer el inventario de iluminación", "Entender el uso y cuidado del equipo de luz"],
    puntosBase: [
      "Par led, moving heads, wash, spot, strobes: diferencias y usos",
      "Hazer, consolas de luces, dimmer rack, cableado DMX",
      "En qué tipo de eventos se usa cada equipo",
      "Cuidados básicos y señales de falla",
      "Por qué la iluminación es uno de los elementos más visibles del servicio",
    ],
  },
  {
    numero: 11, bloque: "Bloque C · El inventario", bloqueLetra: "C", semana: 6,
    titulo: "Categorías del inventario: video, estructuras y otros",
    descripcion: "Pantallas, estructuras, entarimado, DJ setup, energía y misceláneos.",
    objetivos: ["Conocer el resto del inventario por categoría", "Entender la función de cada familia de equipo"],
    puntosBase: [
      "Pantallas LED y de proyección: tipos, resolución y usos",
      "Procesadores de video: scalers, switchers, distribuidores",
      "Estructuras: tipos, capacidad de carga, configuraciones",
      "Entarimado: medidas, configuraciones y limitaciones",
      "DJ setup: mixer, platos, controladores",
      "Energía: planta de luz, distribución eléctrica, protección de circuitos",
      "Misceláneos: gaffer, líquido de humo, herramienta, consumibles",
    ],
  },
  {
    numero: 12, bloque: "Bloque D · El show", bloqueLetra: "D", semana: 6,
    titulo: "De qué elementos se compone un show musical",
    descripcion: "PA, delay, front fill, out fill, side fill, pisos, IEM, FOH, monitor world y más.",
    objetivos: ["Entender la arquitectura completa de audio en un show en vivo", "Conocer cada elemento del sistema y su función"],
    puntosBase: [
      "El sistema de PA: función, tipos de configuración y cobertura del venue",
      "Subwoofers: posicionamiento, configuración cardioid y manejo de baja frecuencia",
      "Delay towers: qué son, cuándo se usan y cómo se calculan los tiempos",
      "Front fill: cobertura de primera fila y zona muerta frente al escenario",
      "Out fill: cobertura lateral del venue",
      "Side fill: monitoreo de escenario para músicos en los lados",
      "Pisos (monitores de piso): tipos, posicionamiento y mezclas independientes",
      "Monitoreo IEM (in-ear monitors): funcionamiento y ventajas sobre pisos",
      "Snake y stagebox: distribución de señales entre escenario y FOH",
      "Patch de escenario: organización de entrada de señales",
      "Comunicaciones técnicas (intercom): coordinación durante el evento",
      "Sistema de consolas: FOH vs monitor world",
      "Diseño de iluminación para show en vivo",
      "Coordinación con producción artística: rider y cambios de último momento",
    ],
  },
  {
    numero: 13, bloque: "Bloque D · El show", bloqueLetra: "D", semana: 7,
    titulo: "De qué elementos se compone un evento social",
    descripcion: "Audio para DJ y voz, iluminación de ambiente vs show, pantallas y coordinación con el venue.",
    objetivos: ["Conocer la arquitectura técnica de un evento social", "Entender las diferencias clave vs un show musical"],
    puntosBase: [
      "Audio para DJ: sistema de PA, subwoofers, configuración de sala",
      "Audio para voz: micrófonos inalámbricos, mezcla de voz sobre música",
      "Diferencias entre mezclar música y mezclar voz en el mismo sistema",
      "Iluminación de ambiente: temperatura de color, zonas, efectos sutiles",
      "Iluminación de show o pista: moving heads, strobes, efectos, sincronización",
      "Pantallas y reproducción de video en eventos sociales",
      "Coordinación con el venue, el DJ, el fotógrafo y otros proveedores",
      "Cómo se ve un montaje exitoso en una boda o quinceañera",
    ],
  },
  {
    numero: 14, bloque: "Bloque D · El show", bloqueLetra: "D", semana: 7,
    titulo: "De qué elementos se compone un evento corporativo",
    descripcion: "Conferencia, streaming, video multipantalla y branding lumínico para cliente institucional.",
    objetivos: ["Conocer la arquitectura técnica de un evento corporativo", "Entender el streaming y la distribución de video"],
    puntosBase: [
      "Audio de conferencia: micrófonos de solapa, de mano y de podio",
      "Mezcla de voz para ponentes: claridad, inteligibilidad y control",
      "Sistema de audio distribuido en sala: delay integrado, zonas y niveles",
      "Video: pantallas de proyección vs pantallas LED, señales de presentación",
      "Streaming: captura de audio y video, encoder, plataformas y monitoreo",
      "Cámaras: posiciones, tipos de plano y coordinación con operador",
      "Iluminación de escenario corporativo: key light, fill light, backlight",
      "Gobos y branding lumínico",
      "Coordinación con el cliente institucional y su equipo",
    ],
  },
  {
    numero: 15, bloque: "Bloque E · Personal técnico", bloqueLetra: "E", semana: 8,
    titulo: "Por qué el personal técnico es el corazón de la operación",
    descripcion: "El equipo humano es tan importante como el equipo físico. Cómo se elige y qué significa tener técnicos confiables.",
    objetivos: ["Comprender el valor del capital humano técnico", "Entender cómo se construye un banco de técnicos confiables"],
    puntosBase: [
      "Sin técnicos no hay evento: el equipo humano es tan importante como el físico",
      "Diferencia entre personal de planta y personal freelance",
      "Por qué la calidad del técnico afecta directamente la experiencia del cliente",
      "Cómo se elige y evalúa a un técnico",
      "Qué significa tener un buen banco de técnicos confiables",
      "Cómo se construye una relación profesional con los técnicos freelance",
    ],
  },
  {
    numero: 16, bloque: "Bloque E · Personal técnico", bloqueLetra: "E", semana: 8,
    titulo: "Roles técnicos en un evento",
    descripcion: "FOH, monitores, luces, video, rigging, auxiliar y coordinador de campo. Quién hace qué y cómo interactúan.",
    objetivos: ["Conocer cada rol técnico y sus responsabilidades", "Entender cómo se coordinan los roles durante el evento"],
    puntosBase: [
      "Ingeniero de audio FOH: responsabilidades y criterio de mezcla",
      "Ingeniero de monitores: comunicación con artistas y gestión de escenario",
      "Operador de luces: programación y ejecución en vivo",
      "Operador de video y pantallas: gestión de señales y switching",
      "Rigger y armador de estructuras: criterios de seguridad y protocolos",
      "Cargador y auxiliar de producción: rol en montaje y desmontaje",
      "Coordinador de campo: quién manda y cómo toma decisiones en tiempo real",
      "Cómo interactúan estos roles entre sí durante el evento",
      "Qué pasa cuando un rol falla: contingencias y toma de decisiones",
    ],
  },
  {
    numero: 17, bloque: "Bloque F · Subarriendo", bloqueLetra: "F", semana: 9,
    titulo: "Cuándo y cómo se subarrienda equipo",
    descripcion: "El subarriendo como herramienta estratégica. Cuándo es necesario, cómo se gestiona y qué riesgos tiene.",
    objetivos: ["Entender el subarriendo como herramienta estratégica", "Conocer los riesgos y controles del subarriendo"],
    puntosBase: [
      "Qué es el subarriendo y por qué es parte estratégica del modelo de negocio",
      "Cuándo se subarrienda: falta de equipo, mantenimiento, proyectos grandes",
      "Cómo se elige un proveedor técnico confiable",
      "Riesgos de traer equipo de terceros y cómo gestionarlos",
      "Cómo se documenta y gestiona una subrenta correctamente",
      "Impacto del subarriendo en la rentabilidad del proyecto",
      "Por qué no todo se puede subarrendar: qué equipo debe ser siempre propio",
    ],
  },
  {
    numero: 18, bloque: "Bloque G · Seguridad técnica", bloqueLetra: "G", semana: 9,
    titulo: "Seguridad en eventos: lo que nunca se improvisa",
    descripcion: "Rigging, electricidad, estructuras y protocolos de emergencia. La seguridad no negocia.",
    objetivos: ["Comprender los principios de seguridad técnica en eventos", "Conocer los protocolos de emergencia en campo"],
    puntosBase: [
      "Por qué la seguridad técnica es responsabilidad de todo el equipo",
      "Rigging: capacidad de carga, puntos de anclaje, protocolos de certificación",
      "Seguridad eléctrica: distribución de cargas, protección de circuitos, tierra",
      "Estructuras: revisión de tornillería, estabilidad, condiciones del piso y clima",
      "Manejo seguro de equipos pesados: carga, descarga y movimiento",
      "Protocolos de emergencia en campo",
      "El criterio de Mainstage Pro: nunca comprometer seguridad por tiempo o costo",
    ],
  },
  {
    numero: 19, bloque: "Bloque H · El rider técnico", bloqueLetra: "H", semana: 10,
    titulo: "Cómo se lee y gestiona un rider técnico",
    descripcion: "Qué es un rider, cómo se lee, cómo se negocia y qué hacer cuando no se puede cumplir al 100%.",
    objetivos: ["Saber leer e interpretar un rider técnico", "Aprender a negociar y documentar acuerdos sobre el rider"],
    puntosBase: [
      "Qué es un rider técnico y quién lo elabora",
      "Estructura de un rider: sistema de PA, backline, monitoreo, iluminación",
      "Cómo se lee un rider y cómo se traduce a una lista de equipo real",
      "Qué hacer cuando el rider no se puede cumplir al 100%",
      "Diferencia entre un rider como exigencia y como punto de partida",
      "Cómo documentar los acuerdos post-negociación",
      "Errores comunes al interpretar un rider y cómo evitarlos",
    ],
  },
  {
    numero: 20, bloque: "Bloque I · La operación", bloqueLetra: "I", semana: 10,
    titulo: "De la cotización aprobada al plan de producción",
    descripcion: "El traspaso de ventas a producción: cómo leer una cotización y convertirla en un plan ejecutable.",
    objetivos: ["Entender el proceso de traspaso de ventas a producción", "Saber convertir una cotización en un plan operativo"],
    puntosBase: [
      "Cómo se lee una cotización aprobada desde el lado de producción",
      "Qué información debe llegar completa desde ventas",
      "Identificar equipos necesarios vs equipos disponibles en inventario",
      "Gestionar faltantes: subarriendo, compra de emergencia o ajuste con cliente",
      "Revisar disponibilidad de personal técnico con anticipación",
      "El traspaso de ventas a producción: uno de los momentos más críticos",
    ],
  },
  {
    numero: 21, bloque: "Bloque I · La operación", bloqueLetra: "I", semana: 11,
    titulo: "Coordinación previa al evento",
    descripcion: "Roles, junta previa, checklist de salida y grupo de WhatsApp. Todo lo que pasa antes de salir a campo.",
    objetivos: ["Conocer el proceso de coordinación pre-evento", "Entender la importancia de la junta previa y el checklist"],
    puntosBase: [
      "Asignación de roles al personal técnico: quién hace qué y por qué",
      "Gestión del equipo de trabajo: descansos, relevos, tiempos de traslado",
      "Junta previa al evento: qué se comunica, quién debe estar y por qué es obligatoria",
      "Checklist de salida de equipos: cómo se hace y quién lo valida",
      "Grupo de WhatsApp del evento: información clave antes de salir",
      "Ficha técnica del evento: cómo se lee y quién debe conocerla",
    ],
  },
  {
    numero: 22, bloque: "Bloque I · La operación", bloqueLetra: "I", semana: 11,
    titulo: "El día del evento: de la llegada al desmontaje",
    descripcion: "Llegada, montaje, soundcheck, operación, imprevistos y desmontaje. El ciclo completo del día.",
    objetivos: ["Conocer el ciclo completo del día de evento", "Aprender a gestionar imprevistos en tiempo real"],
    puntosBase: [
      "Llegada al venue: reconocimiento del espacio y coordinación inicial",
      "Montaje ordenado: por qué el orden en el montaje define el orden en la operación",
      "Trato con el cliente durante el evento: comunicación y representación de marca",
      "Soundcheck y pruebas técnicas: tiempos, orden y criterio",
      "Operación técnica durante el show: atención, criterio y comunicación interna",
      "Gestión de imprevistos en tiempo real: cómo se decide, comunica y resuelve",
      "Desmontaje: tan importante como el montaje",
      "Carga y llegada a bodega: el evento no termina hasta que todo está guardado",
    ],
  },
  {
    numero: 23, bloque: "Bloque I · La operación", bloqueLetra: "I", semana: 12,
    titulo: "Carga, descarga y orden en bodega",
    descripcion: "Por qué el orden en bodega es operativo y económico, no estético. Hábito, no tarea extraordinaria.",
    objetivos: ["Comprender la importancia operativa del orden en bodega", "Aprender el sistema de carga y organización correcto"],
    puntosBase: [
      "Por qué la carga y descarga correcta protege el equipo y al equipo",
      "Cómo se carga un vehículo de producción: peso, distribución y fijación",
      "Secuencia de carga: qué va primero, qué va al último y por qué",
      "Por qué el orden en bodega no es estético — es operativo y económico",
      "Sistema de categorías y etiquetado: encontrar cualquier equipo sin depender de nadie",
      "Consecuencias reales de una bodega desordenada",
      "Cómo mantener el orden de bodega como hábito, no como tarea extraordinaria",
    ],
  },
  {
    numero: 24, bloque: "Bloque I · La operación", bloqueLetra: "I", semana: 12,
    titulo: "Cierre de evento y reporte post-producción",
    descripcion: "Revisión, limpieza, reporte, cierre financiero. El evento no termina hasta que el ciclo está cerrado.",
    objetivos: ["Conocer el proceso de cierre completo de un evento", "Entender la importancia de la documentación post-evento"],
    puntosBase: [
      "Revisión y limpieza de equipo al regreso: primer paso antes de guardar",
      "Reporte de coordinación: qué incluye, para qué sirve y cuándo debe estar listo",
      "Documentación de incidencias: daños, faltantes, fallas técnicas",
      "Cierre financiero del evento: costo real vs cotizado",
      "Por qué documentar bien un evento mejora directamente el siguiente",
      "Historial de eventos: cómo se construye la memoria operativa de la empresa",
      "El ciclo completo se cierra cuando el reporte está entregado y el equipo guardado",
    ],
  },
];

async function main() {
  console.log("Seeding sesiones de capacitación...");

  // Clear existing data
  await prisma.versionPresentacion.deleteMany();
  await prisma.sesionCapacitacion.deleteMany();

  for (const s of SESIONES) {
    await prisma.sesionCapacitacion.create({
      data: {
        numero: s.numero,
        titulo: s.titulo,
        bloque: s.bloque,
        bloqueLetra: s.bloqueLetra,
        descripcion: s.descripcion,
        objetivos: s.objetivos,
        puntosBase: s.puntosBase,
        puntosEditados: [],
        semana: s.semana,
        duracion: 60,
        impartidor: "Mauricio Hernández",
        estado: "pendiente",
      },
    });
    console.log(`  ✓ Sesión ${String(s.numero).padStart(2, "0")} — ${s.titulo}`);
  }

  console.log(`\n✅ Seed completado: ${SESIONES.length} sesiones creadas.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
