"use client";

import { useMemo } from "react";

const FRASES: string[] = [
  "El éxito no es el destino, es la dirección.",
  "Cada gran empresa comenzó con una decisión valiente.",
  "Tu red de contactos determina tu valor neto.",
  "Los clientes no compran productos, compran soluciones.",
  "La consistencia supera al talento cuando el talento no es consistente.",
  "Haz lo que amas y el dinero seguirá.",
  "Un equipo motivado puede mover montañas.",
  "La visión sin ejecución es alucinación.",
  "No esperes el momento perfecto, haz perfecto el momento.",
  "El riesgo más grande es no tomar ninguno.",
  "Invierte en tu equipo y ellos invertirán en tu empresa.",
  "Las oportunidades no ocurren, las creas.",
  "Tu reputación es tu activo más valioso.",
  "El crecimiento ocurre fuera de tu zona de confort.",
  "Cada cliente satisfecho es el mejor vendedor.",
  "La simplicidad es la sofisticación máxima.",
  "Falla rápido, aprende más rápido.",
  "El liderazgo es servir, no mandar.",
  "Una buena idea ejecutada hoy vale más que una perfecta mañana.",
  "El mercado recompensa a quien actúa.",
  "Construye sistemas, no dependencias.",
  "La disciplina es la base de todo logro extraordinario.",
  "Un negocio es un reflejo de la persona que lo dirige.",
  "El mejor momento para plantar un árbol fue ayer; el segundo mejor es hoy.",
  "Innova o estanca — no hay término medio.",
  "La gratitud es el mejor imán de abundancia.",
  "Rodéate de personas que te hagan mejor.",
  "Cada 'no' te acerca al 'sí' definitivo.",
  "La excelencia no es un acto, es un hábito.",
  "Piensa en grande, empieza pequeño, actúa ahora.",
  "El servicio extraordinario crea clientes para toda la vida.",
  "Tus limitaciones solo existen en tu mente.",
  "Trabaja en tu negocio, no solo dentro de él.",
  "El propósito multiplica el esfuerzo.",
  "Un problema es una oportunidad disfrazada.",
  "La perseverancia es el secreto de todos los triunfos.",
  "Conoce a tu cliente mejor de lo que él se conoce a sí mismo.",
  "Las empresas que perduran tienen valores que no negocian.",
  "Pregunta siempre: ¿cómo puedo dar más valor?",
  "La velocidad de implementación es una ventaja competitiva.",
  "No compitas en precio, compite en valor.",
  "El detalle marca la diferencia entre lo bueno y lo memorable.",
  "Tu energía es contagiosa — elige cuál transmites.",
  "Construye sobre fortalezas, administra debilidades.",
  "El aprendizaje continuo es el combustible del crecimiento.",
  "Una empresa sin cultura es una empresa sin futuro.",
  "La claridad de objetivos reduce el tiempo de ejecución.",
  "Las crisis revelan el carácter de una organización.",
  "El cliente siempre tiene razón sobre sus sentimientos.",
  "Automatiza lo repetible, humaniza lo memorable.",
  "La confianza se gana en gotas y se pierde en litros.",
  "Mide lo que importa, ignora el ruido.",
  "Un equipo diverso tiene perspectivas más ricas.",
  "La paciencia estratégica es una fortaleza.",
  "Antes de vender, entiende.",
  "Las mejores inversiones son las que generan tiempo libre.",
  "La integridad es el fundamento de toda relación comercial.",
  "Cada decisión que tomas hoy forma la empresa de mañana.",
  "Celebra los logros pequeños — construyen los grandes.",
  "El que no comunica, no existe.",
  "La mentalidad de abundancia abre puertas que la escasez cierra.",
  "Tu mayor competidor eres tú mismo de ayer.",
  "Las empresas escalables tienen procesos replicables.",
  "Sé el tipo de proveedor que te gustaría tener.",
  "La innovación es la única garantía de relevancia.",
  "El liderazgo real se mide en los momentos difíciles.",
  "Escucha el doble de lo que hablas.",
  "Los datos son la brújula, la intuición es el timón.",
  "Construye relaciones antes de necesitarlas.",
  "Un negocio rentable es un negocio que puede hacer bien.",
  "La humildad te permite aprender de todos.",
  "Haz promesas pequeñas y entrega en grande.",
  "La reputación tarda años en construirse y segundos en perderse.",
  "El trabajo en equipo hace que el sueño funcione.",
  "Las métricas sin contexto son ruido.",
  "Quien controla su agenda, controla su destino.",
  "La creatividad resuelve lo que el dinero no puede.",
  "Invertir en experiencias del cliente es invertir en crecimiento.",
  "Sé tan bueno que no puedan ignorarte.",
  "La ejecución imperfecta hoy supera la perfección futura.",
  "Un gran mentor vale más que cualquier curso.",
  "El éxito deja huellas — encuéntralas y síguelas.",
  "La cultura come a la estrategia de desayuno.",
  "Protege tu tiempo como el activo más escaso.",
  "La colaboración amplifica el impacto individual.",
  "Un cliente que regresa es tu mejor indicador de éxito.",
  "La queja de un cliente es un regalo de retroalimentación.",
  "La claridad vende mejor que el carisma.",
  "Invierte en lo que no caduca: conocimiento y relaciones.",
  "La urgencia sin dirección solo crea caos.",
  "Cuando dudes, vuelve a tu propósito.",
  "El foco es el multiplicador del esfuerzo.",
  "No busques trabajo perfecto — crea trabajo con sentido.",
  "La reputación de tu equipo construye la tuya.",
  "Las empresas que escuchan, crecen.",
  "El fracaso informado es un paso hacia adelante.",
  "Comparte conocimiento — lo que das, regresa multiplicado.",
  "La consistencia en la calidad construye marcas eternas.",
  "Cada conversación es una oportunidad de crear valor.",
  "El precio de no crecer es quedarse atrás.",
  "La perseverancia convierte lo imposible en inevitable.",
  "Sueña tan grande que asuste, ejecuta tan bien que sorprenda.",
  "Los mejores líderes crean más líderes.",
  "El mercado no miente — escúchalo.",
  "Una buena pregunta vale más que mil respuestas correctas.",
  "El propósito claro convierte el trabajo en vocación.",
  "Tu actitud en la adversidad define tu liderazgo.",
  "La confianza en tu equipo libera tu energía para lo estratégico.",
  "No hay atajo a un lugar que valga la pena.",
  "Crea valor primero, recibe valor después.",
  "El seguimiento convierte prospectos en clientes.",
  "La atención al detalle es un diferenciador invisible pero poderoso.",
  "Todo negocio exitoso resuelve un problema real.",
  "La retroalimentación honesta es el regalo más valioso.",
  "La estabilidad financiera da libertad de elegir.",
  "Quien aprende de sus errores gana; quien los repite, pierde.",
  "El carisma abre puertas, la confiabilidad las mantiene abiertas.",
  "Invierte en sistemas que trabajen cuando tú no puedas.",
  "El cliente que confía en ti no busca precio, busca seguridad.",
  "Las grandes empresas nacen de grandes preguntas.",
  "La humildad intelectual es la puerta al aprendizaje continuo.",
  "Delega la tarea, conserva la responsabilidad.",
  "Cuando el propósito es claro, la motivación es natural.",
  "La adaptabilidad es la habilidad del siglo XXI.",
  "Cada queja resuelta crea un embajador de marca.",
  "Mide resultados, no horas.",
  "El tiempo de calidad con tu equipo es tiempo de inversión.",
  "La estrategia sin cultura es un plan en papel.",
  "El cliente ideal existe — encuéntralo y sírvelo magistralmente.",
  "La visión compartida es la mayor fuente de energía organizacional.",
  "No temas crecer — teme quedarte donde estás.",
  "La autenticidad en los negocios genera lealtad real.",
  "Quien domina su nicho, domina su mercado.",
  "La simplicidad operativa reduce costos y aumenta satisfacción.",
  "Un proceso documentado es un negocio escalable.",
  "La urgencia de aprender nunca debe descansar.",
  "Las decisiones rápidas con información incompleta son parte del juego.",
  "La marca es lo que dicen de ti cuando no estás.",
  "El liderazgo se practica en las pequeñas decisiones diarias.",
  "Un cliente feliz habla con tres; uno insatisfecho habla con treinta.",
  "La generosidad estratégica construye redes de valor.",
  "La claridad financiera es libertad empresarial.",
  "El éxito compartido une al equipo más que el discurso.",
  "La estructura libera la creatividad.",
  "Toda empresa es un problema de comunicación esperando solución.",
  "Las personas correctas en los lugares correctos lo cambian todo.",
  "El tiempo dedicado a la planificación multiplica el de ejecución.",
  "Un negocio sin números claros navega sin brújula.",
  "La credibilidad se construye cumpliendo lo prometido.",
  "Cada interacción con el cliente es una actuación de tu marca.",
  "El optimismo realista es la actitud del emprendedor exitoso.",
  "Habla menos de lo que harás y más de lo que ya hiciste.",
  "La innovación incremental supera a la revolución que no llega.",
  "La experiencia del cliente comienza antes de la compra.",
  "Los negocios de impacto duran; los de oportunismo, no.",
  "Tu equipo es el espejo de tu liderazgo.",
  "Construye para la década, opera para el trimestre.",
  "La congruencia entre lo que dices y haces es tu mayor activo.",
  "Las decisiones de hoy son los resultados de mañana.",
  "Sé obsesivo con el cliente, no con la competencia.",
  "El conocimiento sin aplicación es solo potencial.",
  "Cada día sin aprender es un día perdido.",
  "La resiliencia es el músculo más importante del emprendedor.",
  "Los problemas grandes tienen soluciones elegantes si te das tiempo.",
  "El flujo de caja es el oxígeno de tu negocio.",
  "La confianza se construye en silencio, con resultados.",
  "Un negocio bien operado genera paz mental.",
  "La diferenciación elimina la competencia por precio.",
  "El propósito es el norte que nunca cambia.",
  "Ejecuta con urgencia, piensa con calma.",
  "La mejor publicidad es un trabajo bien hecho.",
  "El respeto mutuo es la base de toda sociedad exitosa.",
  "Aprende de todos, no te rindas ante nadie.",
  "Los números no mienten — escúchalos.",
  "La calidad atrae calidad en clientes, socios y oportunidades.",
  "Cada obstáculo contiene la semilla de una solución.",
  "Un mentor reduce décadas a años.",
  "La transparencia genera confianza más rápido que cualquier marketing.",
  "El presente es el único tiempo en que puedes actuar.",
  "Haz que cada cliente sienta que es el único.",
  "La planificación evita la improvisación costosa.",
  "El orden interno produce resultados externos.",
  "Las empresas que perduran tienen misiones que trascienden las ganancias.",
  "Quien cuida a su equipo, cuida a su empresa.",
  "La escucha activa es la habilidad más subestimada en los negocios.",
  "Cada año que no creces, retrocedes.",
  "El silencio estratégico a veces comunica más que mil palabras.",
  "La mentalidad de crecimiento convierte retos en oportunidades.",
  "Los mercados cambian; los valores, no.",
  "La humildad de servir es la nobleza del empresario.",
  "Un equipo que se divierte, produce más.",
  "La confianza en el proceso es la calma del estratega.",
  "El éxito de tu cliente es tu mejor caso de estudio.",
  "Quien se conoce a sí mismo, lidera mejor.",
  "La velocidad de adaptación determina la longevidad del negocio.",
  "No temas cobrar lo que vales.",
  "El pensamiento a largo plazo es el privilegio de los disciplinados.",
  "Una empresa sana tiene finanzas sanas y equipo motivado.",
  "La pasión sin dirección es energía desperdiciada.",
  "El seguimiento postventa crea clientes de por vida.",
  "Toda gran historia empresarial comenzó con una decisión incómoda.",
  "La cultura de excelencia se filtra de arriba hacia abajo.",
  "Invertir en tu salud es invertir en tu productividad.",
  "La gratitud hacia tu equipo multiplica su compromiso.",
  "Quien gestiona su energía gestiona su impacto.",
  "La honestidad radical acelera la resolución de problemas.",
  "Los líderes se hacen en las dificultades, no en la comodidad.",
  "Un buen sistema hace que el equipo promedio sea extraordinario.",
  "La congruencia entre precio y valor es la base de la confianza.",
  "El mercado premia la especialización.",
  "Comunica la visión hasta que todos puedan repetirla.",
  "La agilidad organizacional vale más que el tamaño.",
  "El error reconocido y corregido fortalece la credibilidad.",
  "La energía que pones hoy regresa transformada mañana.",
  "Las marcas que perduran tocan emociones, no solo necesidades.",
  "El tiempo libre es tiempo de estrategia.",
  "Cuida tu reputación digital tanto como la presencial.",
  "Las alianzas correctas aceleran el crecimiento exponencialmente.",
  "Un buen pitch resuelve el problema del cliente antes de presentar el producto.",
  "La obsesión por mejorar es el combustible de las grandes empresas.",
  "Quien sabe cuándo decir no, protege su sí más valioso.",
  "La diversidad de ideas produce soluciones más robustas.",
  "El entusiasmo genuino vende sin vender.",
  "Cada cliente es una historia de éxito potencial.",
  "La prudencia financiera es el escudo del emprendedor.",
  "Los procesos claros liberan energía creativa.",
  "El aprendizaje de la adversidad es el más duradero.",
  "La ambición con ética construye legados.",
  "Enseña a tu equipo a pensar, no solo a hacer.",
  "La primera impresión es tu contrato de confianza no escrito.",
  "El cliente que se va puede volver; el que se va mal hablado no.",
  "La disciplina financiera hoy compra libertad mañana.",
  "El pensamiento positivo sin acción es solo fantasía.",
  "Quien innova en servicio crea barreras de entrada naturales.",
  "La lealtad del equipo se gana con coherencia, no con palabras.",
  "Cada fracaso bien analizado acelera el siguiente éxito.",
  "El enfoque protege de la mediocridad.",
  "La mentalidad del servicio transforma transacciones en relaciones.",
  "Las grandes ideas necesitan coraje para ejecutarse.",
  "El orden en las finanzas refleja el orden en la mente del empresario.",
  "Celebra los logros de tu equipo en público, corrige en privado.",
  "La confianza en ti mismo es el capital más escaso y más valioso.",
  "Un negocio bien documentado puede sobrevivir la ausencia de su fundador.",
  "La competencia te hace más fuerte si aprendes de ella.",
  "Quien se rodea de los mejores, se convierte en uno de ellos.",
  "La experiencia memorable es el marketing más poderoso.",
  "El cliente no paga por lo que haces, paga por cómo lo haces sentir.",
  "El liderazgo efectivo transforma potencial en resultados.",
  "La claridad de roles elimina el 80% de los conflictos de equipo.",
  "Las crisis bien manejadas crean historias de marca poderosas.",
  "El progreso constante supera al esfuerzo esporádico.",
  "La visión audaz atrae a las personas audaces.",
  "Quien construye valor siempre tendrá mercado.",
  "La comunicación asertiva ahorra tiempo, dinero y conflictos.",
  "Un equipo con propósito común logra lo extraordinario.",
  "La excelencia operativa es una ventaja competitiva sostenible.",
  "Las buenas preguntas abren puertas que las respuestas no pueden.",
  "El networking genuino se basa en dar, no en pedir.",
  "La rentabilidad es el aplauso del mercado a tu propuesta de valor.",
  "Quien mide, mejora; quien ignora los números, improvisa.",
  "La consistencia en la entrega construye reputación irremplazable.",
  "La mentalidad de inversión supera a la mentalidad de gasto.",
  "Un equipo bien entrenado ejecuta mejor bajo presión.",
  "La honestidad con el cliente acelera la relación comercial.",
  "El mejor plan de negocios es uno que se ejecuta.",
  "La fortaleza del equipo está en sus vínculos, no solo en su talento.",
  "Quien controla sus costos, controla su destino.",
  "La visión de largo plazo convierte sacrificios de hoy en ganancias de mañana.",
  "El mercado más rentable es donde tu pasión encuentra una necesidad.",
  "Las empresas que escuchan al cliente primero, ganan siempre.",
  "La gratitud empresarial se expresa con resultados, no solo con palabras.",
  "Haz que cada proceso sea tan bueno que el resultado sea inevitable.",
  "La solidez de una empresa se prueba en las crisis.",
  "El liderazgo transformador cambia personas, no solo procesos.",
  "Cada año de aprendizaje es una inversión con interés compuesto.",
  "La claridad en los acuerdos previene conflictos futuros.",
  "Un negocio que cuida a su comunidad, es cuidado por ella.",
  "La perseverancia inteligente incluye saber cuándo pivotar.",
  "El talento se contrata, el compromiso se cultiva.",
  "La automatización libera tiempo para lo que realmente importa.",
  "Quien define su éxito, no compite contra el de otros.",
  "La marca personal del líder potencia la marca de la empresa.",
  "El agradecimiento sincero retiene al mejor talento.",
  "La curiosidad es el motor de la innovación.",
  "Conocer tus números es conocer tu realidad.",
  "La diferencia entre ordinario y extraordinario es ese esfuerzo extra.",
  "El respeto como cultura reduce la rotación de personal.",
  "Las promesas cumplidas son el contrato más poderoso.",
  "Quien cuida el efectivo, cuida el negocio.",
  "La visibilidad de tu trabajo multiplica sus oportunidades.",
  "El crecimiento orgánico es el más duradero.",
  "La disciplina diaria hace posible el éxito extraordinario.",
  "Un cliente que confía en ti no busca alternativas.",
  "La sabiduría empresarial se construye escuchando a quien ya llegó.",
  "Haz preguntas antes de ofrecer soluciones.",
  "La austeridad estratégica en tiempos de bonanza protege en los difíciles.",
  "El equipo correcto multiplica tus capacidades.",
  "La evolución constante es la única constante del negocio exitoso.",
  "Quien vive sus valores atrae quienes los comparten.",
  "La retroalimentación regular convierte el potencial en desempeño.",
  "El propósito empresarial inspira más que el salario.",
  "El orden en la agenda refleja el orden en las prioridades.",
  "Un cliente bien atendido hoy es un activo para siempre.",
  "La confianza es la moneda más valiosa en cualquier negocio.",
  "Quien aprende a delegar, aprende a crecer.",
  "La mentalidad de abundancia expande lo que la escasez limita.",
  "Cada contacto con el cliente es una oportunidad de reforzar tu marca.",
  "La firmeza en los valores genera respeto duradero.",
  "Haz que tu negocio sea la opción obvia, no la única.",
  "La agilidad para adaptarse es más valiosa que la perfección para planear.",
  "El trabajo bien hecho es el mejor vendedor silencioso.",
  "La inversión en tecnología es inversión en eficiencia.",
  "Quien enseña, aprende dos veces.",
  "Los negocios sostenibles cuidan a sus personas, su propósito y sus finanzas.",
  "La claridad estratégica es el regalo más grande que un líder puede dar a su equipo.",
];

function getDayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / 86400000);
}

export default function DailyGreeting({ nombre }: { nombre: string }) {
  const hoy = useMemo(() => new Date(), []);

  const frase = FRASES[(getDayOfYear(hoy) - 1) % FRASES.length];

  const fecha = hoy.toLocaleDateString("es-MX", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const fechaCapitalizada = fecha.charAt(0).toUpperCase() + fecha.slice(1);
  const primerNombre = nombre.split(" ")[0];

  return (
    <div>
      <h1 className="text-2xl font-bold text-white">
        Hola, {primerNombre}
      </h1>
      <p className="text-[#6b7280] text-sm mt-0.5">{fechaCapitalizada}</p>
      <p className="text-[#B3985B]/80 text-xs mt-2 italic max-w-sm leading-relaxed">
        &ldquo;{frase}&rdquo;
      </p>
    </div>
  );
}
